### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку mutex, Федор Бочаров

### ISSUE THREAD

**Issue by fbocharov** [fbocharov/au-linux-kernel-spring-2016#6]
https://github.com/fbocharov/au-linux-kernel-spring-2016/commit/ad8252cf72a53a241e4fd8dd221ff4ea61ae491d

**Comment by fbocharov** [comment]
Нашел небольшой баг, а так же исправил всякую мелочь. Коммит тут:
https://github.com/fbocharov/au-linux-kernel-spring-2016/commit/d3befc4e944ae9e33ce96b728eceb34e94f4077d

**Comment by eabatalov** [comment]
Hello. Your solution has many bugs. But if we consider its portion that was done right then I estimate that you've done about 65% of task right.
Thank you for the try.
